#!/bin/bash

set -eu

function usage() {
  echo "unit_test <test_name> <generation> "
}

if [[ "$#" -ne 2 ]]; then
  usage
  exit 1
fi
basename=$1
generation=$2


progname=""
if [[ $generation == "1" ]];then
  progname="minigo"
elif [[ $generation == "2" ]]; then
  progname="minigo2"
else
  usage
  exit 1
fi



bin_dir=/tmp/out
tmpfs_dir=/tmp/tmpfs/out
mkdir -p $bin_dir $tmpfs_dir

src=t/$basename/*.go
expected=t/expected/${basename}.txt

as_file=$tmpfs_dir/${basename}.${generation}.s
obj_file=$tmpfs_dir/${basename}.o
bin_file=$bin_dir/${basename}.bin

actual=$tmpfs_dir/actual.txt
# for os.Args
ARGS=t/data/sample.txt

function run_unit_test {
    echo -n "./unit_test $progname $basename ... "

    rm -f $actual
    ./${progname} $src > $as_file
    as -o $obj_file $as_file
    ld -o $bin_file $obj_file
    $bin_file $ARGS > $actual

    diff -u $expected $actual
    if [[ $? -ne 0 ]];then
        echo failed
        return 1
    else
        echo ok
        return 0
    fi
}

run_unit_test
